#!/usr/bin/env python3
"""Generates jni_calls.h: C trampolines for org.lwjgl.system.JNI.call*(args..., fn) natives listed in jni_sigs.txt
(the signatures lwjgl-openvr uses; javap -c its classes | grep org/lwjgl/system/JNI). Apple Silicon LWJGL core
builds omit the OpenVR-only ones, so liblwjgl_openvr registers them at load."""
import os
C = {'I': 'int32_t', 'J': 'int64_t', 'F': 'float', 'D': 'double', 'Z': 'bool', 'S': 'int16_t', 'C': 'uint16_t', 'B': 'int8_t', 'V': 'void'}
here = os.path.dirname(os.path.abspath(__file__))
out, table = [], []
for i, line in enumerate(l.strip() for l in open(os.path.join(here, 'jni_sigs.txt')) if l.strip()):
    name, desc = line.split(':')
    params, ret = desc[1:].split(')')
    args = params[:-1]   # last J is the function address
    decl = ', '.join(f'{C[t]} a{k}' for k, t in enumerate(args))
    ftype = f"{C[ret]} (*)({', '.join(C[t] for t in args) or 'void'})"
    call = f"(({ftype})(intptr_t)fn)({', '.join(f'a{k}' for k in range(len(args)))})"
    body = call + ';' if ret == 'V' else f'return {call};'
    out.append(f"static {C[ret]} j{i}(void *env, void *cls{', ' + decl if decl else ''}, int64_t fn) {{ {body} }}")
    table.append(f'    {{"{name}", "{desc}", (void *)j{i}}},')
with open(os.path.join(here, 'jni_calls.h'), 'w') as f:
    f.write('// Generated by gen_jni_calls.py from jni_sigs.txt. Do not edit.\n')
    f.write('\n'.join(out) + '\n')
    f.write('static const struct { const char *name, *sig; void *fn; } jni_calls[] = {\n' + '\n'.join(table) + '\n};\n')
