#!/usr/bin/env python3
"""Generates jni_calls.h: C trampolines for org.lwjgl.system.JNI.call*(args..., fn) natives listed in jni_sigs.txt
(the signatures lwjgl-openvr uses; javap -c its classes | grep org/lwjgl/system/JNI). Apple Silicon LWJGL core
builds omit the OpenVR-only ones, so liblwjgl_openvr registers them at load."""
import os
import sys
C = {'I': 'int32_t', 'J': 'int64_t', 'F': 'float', 'D': 'double', 'Z': 'bool', 'S': 'int16_t', 'C': 'uint16_t', 'B': 'int8_t', 'V': 'void'}
here = os.path.dirname(os.path.abspath(__file__))
out, table = [], []
seen = set()
for lineno, raw in enumerate(open(os.path.join(here, 'jni_sigs.txt')), 1):
    line = raw.strip()
    if not line:
        continue
    if line in seen:
        sys.exit(f'jni_sigs.txt:{lineno}: duplicate line: {line}')
    seen.add(line)
    try:
        name, desc = line.split(':')
    except ValueError:
        sys.exit(f'jni_sigs.txt:{lineno}: expected name:(ARGS)RET, got: {line!r}')
    if not desc.startswith('(') or ')' not in desc:
        sys.exit(f'jni_sigs.txt:{lineno}: bad descriptor: {desc!r}')
    params, ret = desc[1:].split(')')
    args = params[:-1]   # last J is the function address
    if not params.endswith('J'):
        sys.exit(f'jni_sigs.txt:{lineno}: params must end with the J function address: {desc!r}')
    bad = [t for t in params + ret if t not in C]
    if bad:
        sys.exit(f'jni_sigs.txt:{lineno}: unknown type char(s) {bad}: {desc!r}')
    decl = ', '.join(f'{C[t]} a{k}' for k, t in enumerate(args))
    ftype = f"{C[ret]} (*)({', '.join(C[t] for t in args) or 'void'})"
    call = f"(({ftype})(intptr_t)fn)({', '.join(f'a{k}' for k in range(len(args)))})"
    body = call + ';' if ret == 'V' else f'return {call};'
    out.append(f"static {C[ret]} j{len(out)}(void *env, void *cls{', ' + decl if decl else ''}, int64_t fn) {{ {body} }}")
    table.append(f'    {{"{name}", "{desc}", (void *)j{len(out) - 1}}},')
with open(os.path.join(here, 'jni_calls.h'), 'w') as f:
    f.write('// Generated by gen_jni_calls.py from jni_sigs.txt. Do not edit.\n')
    f.write('#pragma once\n#include <stdbool.h>\n#include <stdint.h>\n')
    f.write('\n'.join(out) + '\n')
    f.write('static const struct { const char *name, *sig; void *fn; } jni_calls[] = {\n' + '\n'.join(table) + '\n};\n')
