// Generated by gen_jni_calls.py from jni_sigs.txt. Do not edit.
#pragma once
#include <stdbool.h>
#include <stdint.h>
static void j0(void *env, void *cls, int32_t a0, int32_t a1, int16_t a2, int64_t fn) { ((void (*)(int32_t, int32_t, int16_t))(intptr_t)fn)(a0, a1, a2); }
static float j1(void *env, void *cls, int64_t fn) { return ((float (*)(void))(intptr_t)fn)(); }
static int32_t j2(void *env, void *cls, int32_t a0, float a1, int64_t fn) { return ((int32_t (*)(int32_t, float))(intptr_t)fn)(a0, a1); }
static int32_t j3(void *env, void *cls, int32_t a0, int64_t fn) { return ((int32_t (*)(int32_t))(intptr_t)fn)(a0); }
static int32_t j4(void *env, void *cls, int64_t fn) { return ((int32_t (*)(void))(intptr_t)fn)(); }
static int64_t j5(void *env, void *cls, int32_t a0, int64_t fn) { return ((int64_t (*)(int32_t))(intptr_t)fn)(a0); }
static int32_t j6(void *env, void *cls, int64_t a0, float a1, float a2, float a3, int64_t fn) { return ((int32_t (*)(int64_t, float, float, float))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j7(void *env, void *cls, int64_t a0, float a1, int64_t fn) { return ((int32_t (*)(int64_t, float))(intptr_t)fn)(a0, a1); }
static int32_t j8(void *env, void *cls, int64_t a0, int32_t a1, int64_t fn) { return ((int32_t (*)(int64_t, int32_t))(intptr_t)fn)(a0, a1); }
static int32_t j9(void *env, void *cls, int64_t a0, int32_t a1, bool a2, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, bool))(intptr_t)fn)(a0, a1, a2); }
static int32_t j10(void *env, void *cls, int64_t a0, int64_t fn) { return ((int32_t (*)(int64_t))(intptr_t)fn)(a0); }
static int64_t j11(void *env, void *cls, int64_t a0, int64_t fn) { return ((int64_t (*)(int64_t))(intptr_t)fn)(a0); }
static int32_t j12(void *env, void *cls, int64_t a0, float a1, float a2, float a3, float a4, int64_t a5, int64_t fn) { return ((int32_t (*)(int64_t, float, float, float, float, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j13(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { return ((int32_t (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static int32_t j14(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j15(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j16(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t a3, int32_t a4, int64_t a5, int64_t a6, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int64_t, int32_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5, a6); }
static int32_t j17(void *env, void *cls, int64_t a0, int32_t a1, int32_t a2, int64_t a3, int32_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j18(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j19(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j20(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int32_t a3, int32_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int32_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j21(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j22(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j23(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { return ((int32_t (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static int32_t j24(void *env, void *cls, int64_t a0, int32_t a1, float a2, int64_t a3, int32_t a4, int64_t a5, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, float, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j25(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j26(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j27(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t a4, int32_t a5, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j28(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j29(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int64_t a3, int32_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j30(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int32_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j31(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j32(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int32_t a3, int32_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int32_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j33(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j34(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j35(void *env, void *cls, int64_t a0, int32_t a1, int32_t a2, int32_t a3, int64_t a4, int32_t a5, int64_t a6, bool a7, int64_t a8, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int32_t, int32_t, int64_t, int32_t, int64_t, bool, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5, a6, a7, a8); }
static int32_t j36(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int64_t a3, int64_t a4, int32_t a5, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j37(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j38(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j39(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6, int64_t a7, int64_t a8, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5, a6, a7, a8); }
static bool j40(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t fn) { return ((bool (*)(int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static void j41(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { ((void (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static bool j42(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t fn) { return ((bool (*)(int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2); }
static bool j43(void *env, void *cls, int64_t a0, int64_t fn) { return ((bool (*)(int64_t))(intptr_t)fn)(a0); }
static int64_t j44(void *env, void *cls, int32_t a0, int64_t fn) { return ((int64_t (*)(int32_t))(intptr_t)fn)(a0); }
static int64_t j45(void *env, void *cls, int64_t fn) { return ((int64_t (*)(void))(intptr_t)fn)(); }
static float j46(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int64_t fn) { return ((float (*)(int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j47(void *env, void *cls, int32_t a0, int32_t a1, int32_t a2, float a3, float a4, int64_t a5, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int32_t, float, float, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j48(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j49(void *env, void *cls, int32_t a0, int64_t a1, int32_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int32_t, int64_t, int32_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j50(void *env, void *cls, int32_t a0, int64_t a1, int32_t a2, int64_t fn) { return ((int32_t (*)(int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j51(void *env, void *cls, int32_t a0, int64_t a1, int64_t fn) { return ((int32_t (*)(int32_t, int64_t))(intptr_t)fn)(a0, a1); }
static int32_t j52(void *env, void *cls, int64_t a0, int32_t a1, int32_t a2, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int32_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j53(void *env, void *cls, int64_t a0, int32_t a1, int64_t fn) { return ((int32_t (*)(int64_t, int32_t))(intptr_t)fn)(a0, a1); }
static int32_t j54(void *env, void *cls, int64_t a0, int64_t fn) { return ((int32_t (*)(int64_t))(intptr_t)fn)(a0); }
static int32_t j55(void *env, void *cls, int64_t a0, bool a1, int64_t fn) { return ((int32_t (*)(int64_t, bool))(intptr_t)fn)(a0, a1); }
static int64_t j56(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int64_t fn) { return ((int64_t (*)(int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int64_t j57(void *env, void *cls, int64_t a0, int64_t fn) { return ((int64_t (*)(int64_t))(intptr_t)fn)(a0); }
static int32_t j58(void *env, void *cls, int64_t a0, int32_t a1, int32_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j59(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, bool a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, bool))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j60(void *env, void *cls, int32_t a0, int32_t a1, int32_t a2, int64_t a3, int32_t a4, int64_t a5, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int32_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j61(void *env, void *cls, int32_t a0, int32_t a1, int32_t a2, int64_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int32_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j62(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j63(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j64(void *env, void *cls, int32_t a0, int64_t a1, int32_t a2, int64_t a3, int32_t a4, int64_t fn) { return ((int32_t (*)(int32_t, int64_t, int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j65(void *env, void *cls, int32_t a0, int64_t a1, int64_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int32_t, int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j66(void *env, void *cls, int32_t a0, int64_t a1, int64_t a2, int64_t fn) { return ((int32_t (*)(int32_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j67(void *env, void *cls, int64_t a0, int32_t a1, int32_t a2, int32_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j68(void *env, void *cls, int64_t a0, int32_t a1, int32_t a2, int64_t a3, int32_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j69(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j70(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int32_t, int32_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j71(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j72(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { return ((int32_t (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static int64_t j73(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int64_t fn) { return ((int64_t (*)(int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int64_t j74(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { return ((int64_t (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static int32_t j75(void *env, void *cls, int32_t a0, int32_t a1, int32_t a2, int64_t a3, int32_t a4, int64_t a5, bool a6, int64_t a7, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int32_t, int64_t, int32_t, int64_t, bool, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5, a6, a7); }
static bool j76(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t fn) { return ((bool (*)(int64_t, int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static float j77(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t fn) { return ((float (*)(int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j78(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int32_t, int32_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j79(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t a4, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static int32_t j80(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int32_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j81(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j82(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int32_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j83(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static int32_t j84(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int32_t a3, int32_t a4, int64_t a5, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static int32_t j85(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static int32_t j86(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t fn) { return ((int32_t (*)(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static bool j87(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t fn) { return ((bool (*)(int64_t, int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static void j88(void *env, void *cls, int32_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t fn) { ((void (*)(int32_t, int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static void j89(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int32_t a3, int64_t a4, int64_t fn) { ((void (*)(int64_t, int64_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static void j90(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t fn) { ((void (*)(int64_t, int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static void j91(void *env, void *cls, int64_t a0, int64_t a1, float a2, int64_t a3, int64_t fn) { ((void (*)(int64_t, int64_t, float, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static void j92(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t a3, int64_t fn) { ((void (*)(int64_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static void j93(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t fn) { ((void (*)(int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static void j94(void *env, void *cls, int64_t a0, int64_t a1, bool a2, int64_t a3, int64_t fn) { ((void (*)(int64_t, int64_t, bool, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static bool j95(void *env, void *cls, int64_t a0, int64_t a1, int64_t a2, int64_t fn) { return ((bool (*)(int64_t, int64_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static void j96(void *env, void *cls, int64_t a0, int32_t a1, float a2, int64_t a3, int64_t fn) { ((void (*)(int64_t, int32_t, float, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static void j97(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int64_t fn) { ((void (*)(int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static void j98(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { ((void (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static bool j99(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int32_t a3, int64_t a4, int64_t fn) { return ((bool (*)(int32_t, int32_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3, a4); }
static bool j100(void *env, void *cls, int32_t a0, int64_t a1, int32_t a2, int64_t a3, int64_t fn) { return ((bool (*)(int32_t, int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static bool j101(void *env, void *cls, int64_t a0, int32_t a1, int64_t a2, int64_t fn) { return ((bool (*)(int64_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static bool j102(void *env, void *cls, int64_t a0, int64_t a1, int32_t a2, int64_t fn) { return ((bool (*)(int64_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2); }
static bool j103(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { return ((bool (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static void j104(void *env, void *cls, int32_t a0, float a1, int64_t a2, int32_t a3, int64_t fn) { ((void (*)(int32_t, float, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2, a3); }
static void j105(void *env, void *cls, int32_t a0, int64_t a1, int64_t fn) { ((void (*)(int32_t, int64_t))(intptr_t)fn)(a0, a1); }
static void j106(void *env, void *cls, int64_t a0, int32_t a1, int64_t fn) { ((void (*)(int64_t, int32_t))(intptr_t)fn)(a0, a1); }
static void j107(void *env, void *cls, int64_t a0, int64_t fn) { ((void (*)(int64_t))(intptr_t)fn)(a0); }
static bool j108(void *env, void *cls, int32_t a0, float a1, float a2, int64_t a3, int64_t fn) { return ((bool (*)(int32_t, float, float, int64_t))(intptr_t)fn)(a0, a1, a2, a3); }
static bool j109(void *env, void *cls, int32_t a0, int32_t a1, int64_t a2, int64_t fn) { return ((bool (*)(int32_t, int32_t, int64_t))(intptr_t)fn)(a0, a1, a2); }
static bool j110(void *env, void *cls, int32_t a0, int64_t a1, int32_t a2, int64_t fn) { return ((bool (*)(int32_t, int64_t, int32_t))(intptr_t)fn)(a0, a1, a2); }
static bool j111(void *env, void *cls, int32_t a0, int64_t a1, int64_t fn) { return ((bool (*)(int32_t, int64_t))(intptr_t)fn)(a0, a1); }
static bool j112(void *env, void *cls, int64_t a0, int32_t a1, int64_t fn) { return ((bool (*)(int64_t, int32_t))(intptr_t)fn)(a0, a1); }
static bool j113(void *env, void *cls, int64_t a0, int64_t fn) { return ((bool (*)(int64_t))(intptr_t)fn)(a0); }
static void j114(void *env, void *cls, float a0, float a1, float a2, float a3, float a4, bool a5, int64_t fn) { ((void (*)(float, float, float, float, float, bool))(intptr_t)fn)(a0, a1, a2, a3, a4, a5); }
static void j115(void *env, void *cls, float a0, float a1, int64_t fn) { ((void (*)(float, float))(intptr_t)fn)(a0, a1); }
static void j116(void *env, void *cls, float a0, bool a1, int64_t fn) { ((void (*)(float, bool))(intptr_t)fn)(a0, a1); }
static void j117(void *env, void *cls, int32_t a0, int32_t a1, int64_t fn) { ((void (*)(int32_t, int32_t))(intptr_t)fn)(a0, a1); }
static void j118(void *env, void *cls, int32_t a0, int32_t a1, int16_t a2, int64_t fn) { ((void (*)(int32_t, int32_t, int16_t))(intptr_t)fn)(a0, a1, a2); }
static void j119(void *env, void *cls, int32_t a0, int64_t fn) { ((void (*)(int32_t))(intptr_t)fn)(a0); }
static void j120(void *env, void *cls, int64_t fn) { ((void (*)(void))(intptr_t)fn)(); }
static void j121(void *env, void *cls, bool a0, int64_t fn) { ((void (*)(bool))(intptr_t)fn)(a0); }
static bool j122(void *env, void *cls, int32_t a0, int64_t fn) { return ((bool (*)(int32_t))(intptr_t)fn)(a0); }
static bool j123(void *env, void *cls, int64_t fn) { return ((bool (*)(void))(intptr_t)fn)(); }
static bool j124(void *env, void *cls, bool a0, int64_t fn) { return ((bool (*)(bool))(intptr_t)fn)(a0); }
static int32_t j125(void *env, void *cls, int64_t fn) { return ((int32_t (*)(void))(intptr_t)fn)(); }
static int64_t j126(void *env, void *cls, int32_t a0, int64_t fn) { return ((int64_t (*)(int32_t))(intptr_t)fn)(a0); }
static int64_t j127(void *env, void *cls, int64_t fn) { return ((int64_t (*)(void))(intptr_t)fn)(); }
static int32_t j128(void *env, void *cls, int64_t a0, int32_t a1, int64_t fn) { return ((int32_t (*)(int64_t, int32_t))(intptr_t)fn)(a0, a1); }
static int64_t j129(void *env, void *cls, int64_t a0, int64_t a1, int64_t fn) { return ((int64_t (*)(int64_t, int64_t))(intptr_t)fn)(a0, a1); }
static bool j130(void *env, void *cls, int64_t a0, int64_t fn) { return ((bool (*)(int64_t))(intptr_t)fn)(a0); }
static void j131(void *env, void *cls, int64_t fn) { ((void (*)(void))(intptr_t)fn)(); }
static bool j132(void *env, void *cls, int64_t fn) { return ((bool (*)(void))(intptr_t)fn)(); }
static const struct { const char *name, *sig; void *fn; } jni_calls[] = {
    {"callCV", "(IISJ)V", (void *)j0},
    {"callF", "(J)F", (void *)j1},
    {"callI", "(IFJ)I", (void *)j2},
    {"callI", "(IJ)I", (void *)j3},
    {"callI", "(J)I", (void *)j4},
    {"callJ", "(IJ)J", (void *)j5},
    {"callJI", "(JFFFJ)I", (void *)j6},
    {"callJI", "(JFJ)I", (void *)j7},
    {"callJI", "(JIJ)I", (void *)j8},
    {"callJI", "(JIZJ)I", (void *)j9},
    {"callJI", "(JJ)I", (void *)j10},
    {"callJJ", "(JJ)J", (void *)j11},
    {"callJJI", "(JFFFFJJ)I", (void *)j12},
    {"callJJI", "(JJJ)I", (void *)j13},
    {"callJJPI", "(JJJIJ)I", (void *)j14},
    {"callJJPI", "(JJJJ)I", (void *)j15},
    {"callJJPPPI", "(JJIJIJJJ)I", (void *)j16},
    {"callJPI", "(JIIJIJ)I", (void *)j17},
    {"callJPI", "(JIJIJ)I", (void *)j18},
    {"callJPI", "(JIJJ)I", (void *)j19},
    {"callJPI", "(JJIIIJ)I", (void *)j20},
    {"callJPI", "(JJIIJ)I", (void *)j21},
    {"callJPI", "(JJIJ)I", (void *)j22},
    {"callJPI", "(JJJ)I", (void *)j23},
    {"callJPJI", "(JIFJIJJ)I", (void *)j24},
    {"callJPJI", "(JIJIJJ)I", (void *)j25},
    {"callJPJI", "(JJIJJ)I", (void *)j26},
    {"callJPPI", "(JIJIJIJ)I", (void *)j27},
    {"callJPPI", "(JIJIJJ)I", (void *)j28},
    {"callJPPI", "(JIJJIJ)I", (void *)j29},
    {"callJPPI", "(JJIIJJ)I", (void *)j30},
    {"callJPPI", "(JJIJJ)I", (void *)j31},
    {"callJPPI", "(JJJIIJ)I", (void *)j32},
    {"callJPPI", "(JJJIJ)I", (void *)j33},
    {"callJPPI", "(JJJJ)I", (void *)j34},
    {"callJPPJI", "(JIIIJIJZJJ)I", (void *)j35},
    {"callJPPPI", "(JIJJJIJ)I", (void *)j36},
    {"callJPPPI", "(JJIJJJ)I", (void *)j37},
    {"callJPPPI", "(JJJJJ)I", (void *)j38},
    {"callJPPPPPPPPI", "(JJJJJJJJJJ)I", (void *)j39},
    {"callJPPZ", "(JJJJ)Z", (void *)j40},
    {"callJPV", "(JJJ)V", (void *)j41},
    {"callJPZ", "(JJIJ)Z", (void *)j42},
    {"callJZ", "(JJ)Z", (void *)j43},
    {"callP", "(IJ)J", (void *)j44},
    {"callP", "(J)J", (void *)j45},
    {"callPF", "(IIJJ)F", (void *)j46},
    {"callPI", "(IIIFFJJ)I", (void *)j47},
    {"callPI", "(IIJJ)I", (void *)j48},
    {"callPI", "(IJIIJ)I", (void *)j49},
    {"callPI", "(IJIJ)I", (void *)j50},
    {"callPI", "(IJJ)I", (void *)j51},
    {"callPI", "(JIIJ)I", (void *)j52},
    {"callPI", "(JIJ)I", (void *)j53},
    {"callPI", "(JJ)I", (void *)j54},
    {"callPI", "(JZJ)I", (void *)j55},
    {"callPJ", "(IIJJ)J", (void *)j56},
    {"callPJ", "(JJ)J", (void *)j57},
    {"callPJI", "(JIIJJ)I", (void *)j58},
    {"callPJJI", "(JJJZJ)I", (void *)j59},
    {"callPPI", "(IIIJIJJ)I", (void *)j60},
    {"callPPI", "(IIIJJJ)I", (void *)j61},
    {"callPPI", "(IIJIJJ)I", (void *)j62},
    {"callPPI", "(IIJJJ)I", (void *)j63},
    {"callPPI", "(IJIJIJ)I", (void *)j64},
    {"callPPI", "(IJJIJ)I", (void *)j65},
    {"callPPI", "(IJJJ)I", (void *)j66},
    {"callPPI", "(JIIIJJ)I", (void *)j67},
    {"callPPI", "(JIIJIJ)I", (void *)j68},
    {"callPPI", "(JIJIJ)I", (void *)j69},
    {"callPPI", "(JJIIIIJ)I", (void *)j70},
    {"callPPI", "(JJIJ)I", (void *)j71},
    {"callPPI", "(JJJ)I", (void *)j72},
    {"callPPJ", "(JIJJ)J", (void *)j73},
    {"callPPJ", "(JJJ)J", (void *)j74},
    {"callPPJI", "(IIIJIJZJJ)I", (void *)j75},
    {"callPPJPPZ", "(JJJJJJ)Z", (void *)j76},
    {"callPPPF", "(JJJJ)F", (void *)j77},
    {"callPPPI", "(IIJJJJ)I", (void *)j78},
    {"callPPPI", "(JIJIJJ)I", (void *)j79},
    {"callPPPI", "(JIJJJ)I", (void *)j80},
    {"callPPPI", "(JJIJJ)I", (void *)j81},
    {"callPPPI", "(JJJIJ)I", (void *)j82},
    {"callPPPI", "(JJJJ)I", (void *)j83},
    {"callPPPPI", "(JJJIIJJ)I", (void *)j84},
    {"callPPPPI", "(JJJJJ)I", (void *)j85},
    {"callPPPPPPI", "(JJJJJJJ)I", (void *)j86},
    {"callPPPPPZ", "(JJJJJJ)Z", (void *)j87},
    {"callPPPPV", "(IJJJJJ)V", (void *)j88},
    {"callPPPPV", "(JJJIJJ)V", (void *)j89},
    {"callPPPPV", "(JJJJJ)V", (void *)j90},
    {"callPPPV", "(JJFJJ)V", (void *)j91},
    {"callPPPV", "(JJIJJ)V", (void *)j92},
    {"callPPPV", "(JJJJ)V", (void *)j93},
    {"callPPPV", "(JJZJJ)V", (void *)j94},
    {"callPPPZ", "(JJJJ)Z", (void *)j95},
    {"callPPV", "(JIFJJ)V", (void *)j96},
    {"callPPV", "(JIJJ)V", (void *)j97},
    {"callPPV", "(JJJ)V", (void *)j98},
    {"callPPZ", "(IIJIJJ)Z", (void *)j99},
    {"callPPZ", "(IJIJJ)Z", (void *)j100},
    {"callPPZ", "(JIJJ)Z", (void *)j101},
    {"callPPZ", "(JJIJ)Z", (void *)j102},
    {"callPPZ", "(JJJ)Z", (void *)j103},
    {"callPV", "(IFJIJ)V", (void *)j104},
    {"callPV", "(IJJ)V", (void *)j105},
    {"callPV", "(JIJ)V", (void *)j106},
    {"callPV", "(JJ)V", (void *)j107},
    {"callPZ", "(IFFJJ)Z", (void *)j108},
    {"callPZ", "(IIJJ)Z", (void *)j109},
    {"callPZ", "(IJIJ)Z", (void *)j110},
    {"callPZ", "(IJJ)Z", (void *)j111},
    {"callPZ", "(JIJ)Z", (void *)j112},
    {"callPZ", "(JJ)Z", (void *)j113},
    {"callV", "(FFFFFZJ)V", (void *)j114},
    {"callV", "(FFJ)V", (void *)j115},
    {"callV", "(FZJ)V", (void *)j116},
    {"callV", "(IIJ)V", (void *)j117},
    {"callV", "(IISJ)V", (void *)j118},
    {"callV", "(IJ)V", (void *)j119},
    {"callV", "(J)V", (void *)j120},
    {"callV", "(ZJ)V", (void *)j121},
    {"callZ", "(IJ)Z", (void *)j122},
    {"callZ", "(J)Z", (void *)j123},
    {"callZ", "(ZJ)Z", (void *)j124},
    {"invokeI", "(J)I", (void *)j125},
    {"invokeP", "(IJ)J", (void *)j126},
    {"invokeP", "(J)J", (void *)j127},
    {"invokePI", "(JIJ)I", (void *)j128},
    {"invokePPP", "(JJJ)J", (void *)j129},
    {"invokePZ", "(JJ)Z", (void *)j130},
    {"invokeV", "(J)V", (void *)j131},
    {"invokeZ", "(J)Z", (void *)j132},
};
